### ISSUE TITLE
Improve the icon

### ISSUE THREAD

**Issue by FJduFou** [turbolocust/SimpleZIP#5]
I worked on the icon to make it more readable despite the size reduction and thus the pixelation.
I give you my current result, there is in addition the addition of a color gradient and the rounding of the corners.
![image](https://user-images.githubusercontent.com/46401854/83969342-c67d0480-a8cf-11ea-8c74-67795c743ca9.png)

**Comment by turbolocust** [comment]
Thanks for the proposal, the icon looks good! I know the current one is not the optimum (graphic design is not my strong suit) and actually I also don't like it. I think I just went looking on the web for a Public Domain icon and transformed it. Anyway, I'm glad you took the effort to improve the current one. **Are you still working on this?** I would very much like to update the current icon to this one and also attribute your work in the application.

**Comment by FJduFou** [comment]
Tell me what you want and i will

**Comment by turbolocust** [comment]
Actually I'm already satisfied with your first draft. I'm just wondering how it would look like if the whole application name (SimpleZIP) was in the box instead of SZIP. At least in the splash screen (the one that is shown when the application starts) I would probably prefer such a version.

If you told me that's not a good idea I would stick with the current version of yours, because as I said I'm not an expert. After all I'm glad someone takes the effort to contribute something :)

**Comment by FJduFou** [comment]
Indeed, it is in my opinion a bad idea because it complicates the logo which according to me must remain simple.
I can still do it if you want

**Comment by turbolocust** [comment]
I understand. Then let's go with simple. I'll create new assets probably by tomorrow if time allows it and let you know once it's done.

**Comment by FJduFou** [comment]
ok

**Comment by turbolocust** [comment]
I pushed the new changes to the master branch. Feel free to check them out.

**Comment by FJduFou** [comment]
can i have a installer pls? 
you have MSIX Packaging Tool for this

**Comment by turbolocust** [comment]
I created an AppxBundle for you via Visual Studio (including x64, x86 and ARM). You can find the bundle [here](https://1drv.ms/u/s!Asj3Z05RGWF1i8l1fVTghdJ4bpArfA?e=YZWlO7). The password to access the download is the name of this application in lowercase. Sideloading of apps must be enabled in Windows. Simply execute the ``Install`` Powershell script once the ZIP was extracted.

**Comment by FJduFou** [comment]
I can't test now, I have a very bad connection where I am. I will tell you that as soon as I have a moment to download what you have given me.

**Comment by turbolocust** [comment]
That's fine, take your time. Just so you know: I had to add a version with inverted colors to support the Windows dark theme properly (especially in the task bar). Check it out, I'm not entirely sure about the color gradient there.

**Comment by FJduFou** [comment]
i can't test but ase for me, it's good

**Comment by FJduFou** [comment]
else, use a blue icon (for exemple), you don't have this problem
![image](https://user-images.githubusercontent.com/46401854/84536953-2bc95f00-acef-11ea-9f40-f1ce8c2d6d40.png)

**Comment by FJduFou** [comment]
or more light:
![image](https://user-images.githubusercontent.com/46401854/84537515-3506fb80-acf0-11ea-980c-e32268c156db.png)

**Comment by turbolocust** [comment]
I'll think about using the blue one for the light version. I'll get back to you probably by tomorrow. I will also add your name to the application's About page to attribute your work on the icon if that's okay with you.

**Comment by FJduFou** [comment]
ok, no problem 😅
my real name is "François-Joseph du Fou"

**Comment by turbolocust** [comment]
I used the lighter blue logo for the dark theme and got rid of the white one. The About page has also been updated. I consider this issue now as resolved and will close it.
